name: release
on:
  workflow_call:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: 1. Checkout
        uses: actions/checkout@v6
      - name: 2. Release
        uses: softprops/action-gh-release@v2
        with:
            generate_release_notes: true
